# Lab assignments
:doctype: article
:encoding: utf-8
:lang: en
:toc: left
:numbered:
:imagesdir: images
:source-language: C

## Booting up in xv6
Compile and run xv6

### Installing tools
For this class you'll need the RISC-V versions of a couple different tools: QEMU 5.1+, GDB 8.3+, GCC, and Binutils. You can install them on Ubuntu 20.04 by:

[source,bash]
----
$ sudo apt-get update && sudo apt-get upgrade
$ sudo apt-get install git build-essential gdb-multiarch qemu-system-misc gcc-riscv64-linux-gnu binutils-riscv64-linux-gnu
----
From Windows, you can access all of your WSL files under the "\\wsl$\" directory. For instance, the home directory for an Ubuntu 20.04 installation should be at "\\wsl$\Ubuntu-20.04\home\<username>\". 

### Compile and run QEMU
To test your installation, you should be able to compile and run xv6.
[source,bash]
---
# in the xv6 directory. dont forget to clone xv6 OS.
$ make qemu
---

NOTE: to quit qemu type Ctrl-a x



## Lab 01: xv6 and Unix utilites
This lab will familiarize you with xv6 and its system calls. We will use xv6 system calls and construct basic UNIX programs like: sleep, pingpong, pipes, find, arguments.


### sleep
Implement the UNIX program sleep for xv6; your sleep should pause for a user-specified number of ticks. A tick is a notion of time defined by the xv6 kernel, namely the time between two interrupts from the timer chip(XV6 defines 100ms timer interrupts). Your solution should be in the file user/sleep.c.

Following the computer stack we can see in the following diagram, the overall structure for system calls(the example is the sleep program):

.system calls in xv6
[uml,file="system_calls_xv6.png"]
--

node "xv6 system calls" {
node "User space"{
    [//sleep.c:\n User calls sleep for "n_ticks"] as sleep
}
node "syscall interface"{
    [//usys.s:\n On startup, system maps shell "sleep" calls to kernel service "sys_sleep"] as usys.s
}
node "Kernel space"{
    [**sys_sleep**\n Kernel retrieves "n_ticks" from process info and \n schedules SLEEPING state until (n_ticks - trap_ticks) == 0"] as sys_sleep
    [**trap**\n calls hardware timer and increases ticks] as trap
    [**process information**\n process->trpframe->a0: n_ticks] as process_info
}
node "Hardware"{
    [**process table**\n processes allocate uc memory at startup.\n Each process has: \n state,\n pid,\n stack,\n size,\n user_table,\n **trapframe**:handles code during traps \n and saves user registers like arguments,\n context: structure for context switches ] as proc
    [**timer tick**\n hardware is programmed to provide 1/10th of a second ticks] as tick
}

[sleep] -d-> [usys.s] : call sleep(n_ticks)
[usys.s] -d-> [sys_sleep] : call sys_sleep()
[sys_sleep] -r-> [process_info] : request "n_ticks" argument
[process_info] -l-> [sys_sleep] : provide "n_ticks" argument
[trap] -down-> [tick] : call timer cycle
[process_info] -down-> [proc] : look for argument\n in process memory 
[trap] -u-> [sys_sleep] : prov/req "trap_ticks"
[sys_sleep] -d-> [trap]  

}
--

#### arguments
command-line arguments are passed from the shell to the kernel using the process memory table. We retrieve the argument from process memory using argint(int an, int *ip) funciton, where an is argument_number and ip is a reference to the storage variable[type uint64].

#### user-kernel space systemcall mapping
xv6 maps user calls to kernel calls by mapping them, using a function pointer in syscall.c. Note that on usys.S and user.h we define the number of syscall to which user call is mapped from.

#### add sleep.c to build
Add your sleep program to UPROGS in Makefile; once you've done that, make qemu will compile your program and you'll be able to run it from the xv6 shell. 



### ping-pong with pipes
Write a program that uses UNIX system calls to ping-pong **a byte between two processes over a pair of pipes, one for each direction**. The parent should send a byte to the child; the child should print "<pid>: received ping", where <pid> is its process ID, write the byte on the pipe to the parent, and exit; the parent should read the byte from the child, print "<pid>: received pong", and exit. Your solution should be in the file user/pingpong.c. 